/// Replays the shared TypeScript/Dart golden corpus at `<repo>/spec/convert/`.
///
/// The corpus is the mechanism ARCHITECTURE-BRIEF §5.2 defines for keeping the
/// two converter implementations honest: one committed set of cases, consumed
/// by `src/main/core/singbox/spec.test.ts` on the desktop side and by this file
/// on the Android side, with `controllerSecret` fixed per case so output is
/// deterministic.
///
/// ```
/// spec/convert/
///   MANIFEST.json          { specVersion, singboxVersion, cases: [...] }
///   cases/<id>/input.yaml      (or input.json)
///   cases/<id>/options.json    { platform, controllerSecret, autoRedirect }
///   cases/<id>/expected.json   canonicalised sing-box JSON
///   cases/<id>/warnings.json
///   cases/<id>/errors.json
/// ```
///
/// The corpus is generated by another workstream and may not exist yet; when
/// `spec/convert/cases` is absent this file skips rather than fails, so a
/// checkout without it still runs green. `test/parity_test.dart` provides the
/// same guarantee against a package-local corpus in the meantime.
library;

import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';

import '../tool/clash_yaml.dart';
import 'support.dart';

void main() {
  final Directory? casesRoot = _findDir('spec/convert/cases');

  group(
    'shared golden corpus',
    () {
      final List<Directory> cases = casesRoot == null
          ? const <Directory>[]
          : (casesRoot.listSync().whereType<Directory>().toList()
            ..sort((Directory a, Directory b) => a.path.compareTo(b.path)));

      test('the corpus has cases', () {
        expect(cases, isNotEmpty);
      });

      test('the manifest declares a spec version', () {
        final File manifest = File(
          '${casesRoot!.parent.path}${Platform.pathSeparator}MANIFEST.json',
        );
        if (!manifest.existsSync()) {
          markTestSkipped('spec/convert/MANIFEST.json not present');
          return;
        }
        final Map<String, dynamic> decoded =
            (jsonDecode(manifest.readAsStringSync()) as Map)
                .cast<String, dynamic>();
        expect(decoded['specVersion'], isNotNull);
      });

      for (final Directory dir in cases) {
        final String id = dir.path.split(Platform.pathSeparator).last;
        test(id, () {
          final Map<String, dynamic> clash = _readInput(dir);
          final ConvertResult result =
              convertClashToSingbox(clash, options: _readOptions(dir));

          final Object? expectedConfig = _readJson(dir, 'expected.json');
          if (expectedConfig != null) {
            const JsonEncoder encoder = JsonEncoder.withIndent('  ');
            expect(
              encoder.convert(result.config),
              encoder.convert(expectedConfig),
            );
          }
          final Object? expectedWarnings = _readJson(dir, 'warnings.json');
          if (expectedWarnings != null) {
            expect(
              result.warnings,
              equals((expectedWarnings as List<Object?>).cast<String>()),
            );
          }
          final Object? expectedErrors = _readJson(dir, 'errors.json');
          if (expectedErrors != null) {
            expect(
              result.errors,
              equals((expectedErrors as List<Object?>).cast<String>()),
            );
          }
          expect(
            expectedConfig ?? expectedWarnings ?? expectedErrors,
            isNotNull,
            reason: 'case "$id" declares nothing to assert',
          );
        });
      }
    },
    skip: casesRoot == null
        ? 'spec/convert/cases not present in this checkout'
        : null,
  );
}

Map<String, dynamic> _readInput(Directory dir) {
  final File yamlFile =
      File('${dir.path}${Platform.pathSeparator}input.yaml');
  if (yamlFile.existsSync()) {
    return parseClashYamlLikeDesktop(yamlFile.readAsStringSync());
  }
  final File jsonFile =
      File('${dir.path}${Platform.pathSeparator}input.json');
  if (jsonFile.existsSync()) {
    return (jsonDecode(jsonFile.readAsStringSync()) as Map)
        .cast<String, dynamic>();
  }
  fail('case ${dir.path} has neither input.yaml nor input.json');
}

ConvertOptions _readOptions(Directory dir) {
  final Object? decoded = _readJson(dir, 'options.json');
  if (decoded is! Map) return const ConvertOptions(platform: '');
  final Map<String, dynamic> map = decoded.cast<String, dynamic>();
  return ConvertOptions(
    platform: (map['platform'] as String?) ?? '',
    controllerSecret: map['controllerSecret'] as String?,
    autoRedirect: (map['autoRedirect'] as bool?) ?? false,
  );
}

Object? _readJson(Directory dir, String name) {
  final File file = File('${dir.path}${Platform.pathSeparator}$name');
  if (!file.existsSync()) return null;
  return jsonDecode(file.readAsStringSync());
}

Directory? _findDir(String relative) {
  final List<String> parts = relative.split('/');
  Directory? dir = Directory.current.absolute;
  for (int depth = 0; depth < 8 && dir != null; depth++) {
    final Directory candidate =
        Directory(<String>[dir.path, ...parts].join(Platform.pathSeparator));
    if (candidate.existsSync()) return candidate;
    final Directory parent = dir.parent;
    dir = parent.path == dir.path ? null : parent;
  }
  return null;
}
